version: '3.8'

services:
  playwright-tests:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    working_dir: /app
    environment:
      - CI=1
      - NODE_ENV=development
      - BASE_URL=${{ secrets.BASE_URL }}
    volumes:
      - ./allure-results:/app/allure-results
    shm_size: '1gb'
    command: ["npm", "test"]
